shared:
twitter:
key: "hrRi9vQI0VeeI4NFLOraDjLDX"  #ここにConsumer Key (API Key)を記述
secret: "xmcFuFuRwkKkklxMqQUEdo1i7iAqhgs3cN31qjEtSuS0MMSXeV" #ここにConsumer Secret (API Secret)を記述
facebook:
key: "587674498455702" #ここにアプリIDを記述
secret: "0d61fa9f563f1b138e29feb8eee6bf50" #ここに app secret を記述